name: compile

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: [standard, mini]
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 core
        run: arduino-cli core install esp32:esp32@3.3.11 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

      - name: Compile examples
        run: tools/compile-examples.sh ${{ matrix.board }}
